//! Class definition via PEP 820 (`PySlot` arrays + `PyType_FromSlots`).
//!
//! A class is a plain Rust payload struct embedded after the `PyObject`
//! header, described by a `static` [`ClassDef`] built with `const fn`s:
//!
//! ```ignore
//! struct Compress { state: Mutex<CompressState> }
//!
//! static COMPRESS_CLASS: ClassDef<Compress> = ClassDef::new(c"zlib._Compress")
//!     .methods(&COMPRESS_METHODS)   // emitted by #[pymethods]
//!     .getsets(&COMPRESS_GETSETS);  // emitted by #[pymethods]
//! ```
//!
//! The type object itself is created at module-exec time with
//! [`ClassDef::create`], which associates it with the module (making
//! `PyType_GetModuleState(defining_class)` work from methods) and stores the
//! `ClassDef`'s address as the type's `Py_tp_token`.
//!
//! Types are final (`Py_TPFLAGS_IMMUTABLETYPE`, no `BASETYPE`) and, unless a
//! `tp_new` is provided, not instantiable from Python
//! (`Py_TPFLAGS_DISALLOW_INSTANTIATION`) — instances are made from Rust
//! factories via [`new_instance`]. Finality is what keeps the
//! defining-class-based module-state lookup safe.

use std::ffi::CStr;
use std::marker::PhantomData;
use std::os::raw::c_void;
use std::ptr::NonNull;

use crate::err::{PyErrRaised, PyResult, PySystemError};
use crate::ffi;
use crate::instance::Bound;
use crate::module::{
    GetSetDefs, MethodDefs, ModuleState, SLOT_END, SlotArray, slot_data, slot_func, slot_size,
    slot_static_data, slot_uint64,
};
use crate::sys_calls;
use crate::threadstate::ThreadState;
use crate::types::{PyAny, PyModule, PyType};

/// `tp_new` slot function type (generated by `#[pymethods]` for `#[new]`).
pub type NewFunc = unsafe extern "C" fn(
    subtype: *mut ffi::PyTypeObject,
    args: *mut ffi::PyObject,
    kwargs: *mut ffi::PyObject,
) -> *mut ffi::PyObject;

/// Byte offset of the `T` payload behind the `PyObject` header.
pub const fn payload_offset<T>() -> usize {
    let header = std::mem::size_of::<ffi::PyObject>();
    let align = std::mem::align_of::<T>();
    header.div_ceil(align) * align
}

/// Raw pointer to the payload of an instance.
///
/// # Safety
///
/// `obj` must be an instance of a type defined by a `ClassDef<T>`.
#[inline]
pub unsafe fn payload_ptr<T>(obj: *mut ffi::PyObject) -> *mut T {
    unsafe { obj.byte_add(payload_offset::<T>()) as *mut T }
}

/// Borrow the payload of an instance.
///
/// # Safety
///
/// `obj` must be a valid instance of a type defined by a `ClassDef<T>`, alive
/// for `'a`.
#[doc(hidden)]
#[inline]
pub unsafe fn payload_ref<'a, T>(obj: *mut ffi::PyObject) -> &'a T {
    unsafe { &*payload_ptr::<T>(obj) }
}

/// `tp_dealloc` for payload-carrying heap types: drop the payload, free the
/// instance, release the reference the instance holds on its heap type.
///
/// Deallocation always runs with an attached thread state, so the payload's
/// `Drop` may (transitively) use TLS-checked reference drops.
///
/// # Safety
///
/// Interpreter-only entry point, installed by `ClassDef`.
unsafe extern "C" fn dealloc_impl<T>(obj: *mut ffi::PyObject) {
    unsafe {
        let tp = (*(obj as *mut ffi::_object)).ob_type;
        std::ptr::drop_in_place(payload_ptr::<T>(obj));
        let free = (*tp).tp_free.unwrap_or(ffi::PyObject_Free);
        free(obj as *mut c_void);
        // Heap-type instances own a reference to their type.
        ffi::Py_DecRef(tp as *mut ffi::PyObject);
    }
}

const MAX_CLASS_SLOTS: usize = 10;

// Fixed indices for slots that builder methods rewrite.
const FLAGS_SLOT: usize = 2;

/// A `const`-built PEP 820 class definition for payload type `T`.
///
/// Must be stored in a `static` (its address becomes the type's
/// `Py_tp_token`).
pub struct ClassDef<T> {
    slots: SlotArray<MAX_CLASS_SLOTS>,
    len: usize,
    _marker: PhantomData<fn() -> T>,
}

// SAFETY: logically immutable after const construction; every stored pointer
// targets 'static data (name string, method/getset tables, glue fns).
unsafe impl<T> Sync for ClassDef<T> {}

impl<T: Send + Sync + 'static> ClassDef<T> {
    /// Start a class definition. `name` is the fully qualified name shown to
    /// Python (e.g. `c"zlib._Compress"`).
    pub const fn new(name: &'static CStr) -> Self {
        // PyType_GenericAlloc guarantees at least pymalloc alignment (8);
        // payloads needing more must not rely on the header offset.
        assert!(
            std::mem::align_of::<T>() <= 8,
            "class payload alignment above 8 is not supported"
        );
        let mut slots = [SLOT_END; MAX_CLASS_SLOTS];
        slots[0] = slot_static_data(ffi::Py_tp_name, name.as_ptr() as *mut c_void);
        slots[1] = slot_size(
            ffi::Py_tp_basicsize,
            (payload_offset::<T>() + std::mem::size_of::<T>()) as ffi::Py_ssize_t,
        );
        slots[FLAGS_SLOT] = slot_uint64(
            ffi::Py_tp_flags,
            (ffi::Py_TPFLAGS_DEFAULT
                | ffi::Py_TPFLAGS_IMMUTABLETYPE
                | ffi::Py_TPFLAGS_DISALLOW_INSTANTIATION) as u64,
        );
        slots[3] = slot_func(
            ffi::Py_tp_dealloc,
            Some(unsafe {
                std::mem::transmute::<
                    unsafe extern "C" fn(*mut ffi::PyObject),
                    unsafe extern "C" fn(),
                >(dealloc_impl::<T>)
            }),
        );
        ClassDef {
            slots: SlotArray(slots),
            len: 4,
            _marker: PhantomData,
        }
    }

    const fn push(mut self, slot: ffi::PySlot) -> Self {
        assert!(self.len < MAX_CLASS_SLOTS - 1, "too many class slots");
        self.slots.0[self.len] = slot;
        self.len += 1;
        self
    }

    /// Attach the method table (emitted by `#[pymethods]`).
    pub const fn methods<const N: usize>(self, defs: &'static MethodDefs<N>) -> Self {
        self.push(slot_static_data(
            ffi::Py_tp_methods,
            defs.0.as_ptr() as *mut c_void,
        ))
    }

    /// Attach the getter table (emitted by `#[pymethods]`).
    pub const fn getsets<const N: usize>(self, defs: &'static GetSetDefs<N>) -> Self {
        self.push(slot_static_data(
            ffi::Py_tp_getset,
            defs.0.as_ptr() as *mut c_void,
        ))
    }

    /// Make the type constructible from Python with the given `tp_new`
    /// (emitted by `#[pymethods]` for a `#[new]` method). Clears
    /// `Py_TPFLAGS_DISALLOW_INSTANTIATION`.
    pub const fn tp_new(mut self, new: NewFunc) -> Self {
        // SAFETY: reading back the value this builder wrote in `new()`.
        let flags = unsafe { self.slots.0[FLAGS_SLOT].__bindgen_anon_2.sl_uint64 };
        self.slots.0[FLAGS_SLOT] = slot_uint64(
            ffi::Py_tp_flags,
            flags & !(ffi::Py_TPFLAGS_DISALLOW_INSTANTIATION as u64),
        );
        self.push(slot_func(
            ffi::Py_tp_new,
            Some(unsafe { std::mem::transmute::<NewFunc, unsafe extern "C" fn()>(new) }),
        ))
    }
}

impl<T> ClassDef<T> {
    /// The type's token: the address of this definition.
    pub fn token(&'static self) -> *mut c_void {
        self as *const Self as *mut c_void
    }

    /// Create the heap type, associated with `module`.
    ///
    /// Called from the module's exec function; the returned type object then
    /// lives in the module state as a `Py<PyType>`. The module association is
    /// what makes `PyType_GetModuleState(defining_class)` (used by methods
    /// with a state parameter) resolve to this module's state.
    pub fn create<'py>(
        &'static self,
        ts: &ThreadState<'py>,
        module: &Bound<'py, PyModule>,
    ) -> PyResult<Bound<'py, PyType>> {
        // The static half of the slots is nested via Py_slot_subslots; the
        // runtime-only slots (module pointer, token) are built on the stack.
        let mut dynamic = [
            slot_data(ffi::Py_tp_module, module.as_ptr() as *mut c_void),
            slot_static_data(ffi::Py_tp_token, self.token()),
            slot_static_data(ffi::Py_slot_subslots, self.slots.as_ptr() as *mut c_void),
            SLOT_END,
        ];
        let ptr = unsafe { sys_calls::type_from_slots(ts, dynamic.as_mut_ptr()) };
        match NonNull::new(ptr) {
            Some(p) => {
                let any = unsafe { Bound::<'_, PyAny>::from_owned_ptr(ts, p) };
                Ok(unsafe { any.cast_unchecked::<PyType>() })
            }
            None => Err(unsafe { PyErrRaised::assume_set(ts) }),
        }
    }
}

/// Allocate an instance of `cls` and move `payload` into it.
///
/// This is the Rust-side constructor used by factory functions (e.g.
/// `compressobj()` building a `_Compress`), and by generated `tp_new` glue.
/// `cls` must be a type created from a `ClassDef<T>` (debug-checked in
/// generated callers via the token where possible).
pub fn new_instance<'py, T: Send + Sync + 'static>(
    ts: &ThreadState<'py>,
    cls: &Bound<'py, PyType>,
    payload: T,
) -> PyResult<Bound<'py, PyAny>> {
    let obj =
        unsafe { sys_calls::type_generic_alloc(ts, cls.as_ptr() as *mut ffi::PyTypeObject, 0) };
    let Some(ptr) = NonNull::new(obj) else {
        return Err(unsafe { PyErrRaised::assume_set(ts) });
    };
    unsafe { payload_ptr::<T>(obj).write(payload) };
    Ok(unsafe { Bound::from_owned_ptr(ts, ptr) })
}

/// Raw-pointer variant of [`new_instance`] for generated `tp_new` glue.
///
/// # Safety
///
/// `cls` must be a valid type object created from a `ClassDef<T>`.
#[doc(hidden)]
pub unsafe fn alloc_with<T: Send + Sync + 'static>(
    ts: &ThreadState<'_>,
    cls: *mut ffi::PyTypeObject,
    payload: T,
) -> PyResult<*mut ffi::PyObject> {
    let obj = unsafe { sys_calls::type_generic_alloc(ts, cls, 0) };
    if obj.is_null() {
        return Err(unsafe { PyErrRaised::assume_set(ts) });
    }
    unsafe { payload_ptr::<T>(obj).write(payload) };
    Ok(obj)
}

/// Borrow the typed module state via a method's defining class
/// (`METH_METHOD` calling convention; generated glue).
///
/// # Safety
///
/// `defining_class` must be the defining class the interpreter passed to a
/// `PyCMethod` trampoline, for a type created by [`ClassDef::create`] from a
/// module whose state type is `T`. Finality of our types guarantees the
/// defining class *is* the created type, making `PyType_GetModuleState`
/// safe (cf. the analogous invariant comment in `Modules/zlibmodule.c`).
#[doc(hidden)]
pub unsafe fn state_from_defining_class<'a, T: ModuleState>(
    ts: &ThreadState<'_>,
    defining_class: *mut ffi::PyTypeObject,
) -> PyResult<&'a T> {
    let ptr = unsafe { sys_calls::type_get_module_state(defining_class) };
    if ptr.is_null() {
        return Err(PySystemError::raise(
            ts,
            "defining class has no module state",
        ));
    }
    // The module state block is a StateStorage<T>; go through the module
    // helper's layout by reinterpreting identically.
    let storage = ptr as *mut crate::module::StateStorage<T>;
    unsafe { crate::module::storage_state_ref(ts, storage) }
}
